[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts = --alluredir=reports/allure-results

# KHAI BÁO MARKERS (Bổ sung phần này để chạy phân loại UI/API trên CI/CD)
markers =
    ui: Danh dau cac kich ban test giao dien Web (Selenium)
    api: Danh dau cac kich ban test kiem thu API (Requests)