name: Allure Report CD

on:
  workflow_run:
    workflows: ["Automation Testing CI"] # Lắng nghe chính xác tên của file CI ở trên
    types:
      - completed

# Cấp quyền ghi trực tiếp vào hạ tầng GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-report:
    runs-on: ubuntu-latest
    # Chạy quy trình CD bất kể CI pass hay fail (để vẫn xem được báo cáo các case bị tạch)
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure' }}

    steps:
    # 1. Checkout code để lấy cấu trúc dự án và các cấu hình lịch sử Allure
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Tải kết quả thô từ workflow CI chuyển sang
    - name: Download Raw Allure Results
      uses: actions/download-artifact@v4
      with:
        name: raw-allure-results
        path: reports/allure-results
        run-id: ${{ github.event.workflow_run.id }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    # 3. Biên dịch dữ liệu thô thành báo cáo Allure dạng HTML 
    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      with:
        allure_results: reports/allure-results
        allure_report: allure-report
        allure_history: allure-history
        keep_reports: 20
        allure_report_url: https://thikim148.github.io/${{ github.event.repository.name }}/

    # 4. Đóng gói thư mục báo cáo (Artifact) của Pages
    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: allure-report

    # 5. Deploy trực tiếp lên hạ tầng GitHub Pages thông qua Action kết nối nội bộ
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4

    # 6. Xuat link báo cáo Allure ra log để tiện theo dõi
    - name: Output Allure Report URL
      if: always() # Luôn xuất link báo cáo ra log, kể cả khi CI pass hay fail
      run: |
        echo "### Allure Report URL" >> $GITHUB_STEP_SUMMARY
        echo "Allure Report URL: https://thikim148.github.io/${{ github.event.repository.name }}/**" >> $GITHUB_STEP_SUMMARY